config/routes.rb
Rails.application.routes.draw do
  resources :personas
  resources :profesiones
  devise_for :users

  resources :barrios
  resources :ciudades do
    get 'search'
  end
  get 'principal/index'
 
  root :to => 'principal#index'

end

app/controllers/profesiones_controller.rb
class ProfesionesController < ApplicationController
  before_action :set_profesion, only: [:show, :edit, :update, :destroy]

  def index
    @fprofesion = initialize_filterrific(
      Profesion,
      params[:filterrific]
    ) or return
    @profesiones = @fprofesion.find.page(params[:page])

    # Respond to html for initial page load and to js for AJAX filter updates.
    respond_to do |format|
      format.html
      format.js
    end
  end

  def show
  end

  def new
    @profesion = Profesion.new
  end

  def edit
  end

  def create
    @profesion = Profesion.new(profesion_params)

    respond_to do |format|
      if @profesion.save
        format.html { redirect_to @profesion, notice: 'Profesion fue creada con éxito.' }
        format.json { render :show, status: :created, location: @profesion }
      else
        format.html { render :new }
        format.json { render json: @profesion.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @profesion.update(profesion_params)
        format.html { redirect_to @profesion, notice: 'Profesion fue actualizada correctamente.' }
        format.json { render :show, status: :ok, location: @profesion }
      else
        format.html { render :edit }
        format.json { render json: @profesion.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @profesion.destroy
    respond_to do |format|
      format.html { redirect_to profesiones_url, notice: 'Profesion fue borrada con éxito.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profesion
      @profesion = Profesion.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def profesion_params
      params.require(:profesion).permit(:codigo, :nombre)
    end
end

app/helpers/profesiones_helper.rb
module ProfesionesHelper
end

app/views/profesiones/_form.html.haml
= form_for @profesion do |f|
  #error_explanation.bg-danger.text-danger
  .row
    .col-sm-6
      .form-group
        = f.label :codigo, :class => "control-label"
        = f.text_field :codigo, :class => "form-control first_input"
      .form-group
        = f.label :nombre, :class => "control-label"
        = f.text_field :nombre, :class => "form-control"
      .form-group
        = f.submit @profesion.new_record? ? "Crear Profesion" : "Actualizar Profesion", :class => "btn btn-primary"

app/views/profesiones/_list.html.haml
%table.table.table-bordered.table-striped
  %tr
    %th Nombre
    %th Codigo
    %th
  - profesiones.each do |profesion|
    %tr
      %td= profesion.nombre
      %td= profesion.codigo
      %td= link_to "Editar", edit_profesion_path(profesion), :class => "btn btn-primary"

.chardin_box{ :'data-position' => 'top', :'data-intro' => "Paginador de will_paginate funciona como se esperaba." }
  = will_paginate profesiones, renderer: BootstrapPagination::Rails

app/views/profesiones/edit.html.haml
%h1 Modificar profesion

= render 'form'

= link_to 'Mostrar', @profesion
\|
= link_to 'Atras', profesiones_path

app/views/profesiones/index.html.haml
.page-header{ :style => 'margin-bottom: 0px;' }
  .pull-right
    = link_to 'Home', root_path, :style => 'display: inline-block; margin-top: 25px;'
  %h1 Profesiones

.well
  = form_for_filterrific @fprofesion do |f|
    .row
      .col-md-3
        .form-group.chardin_box{ :'data-position' => 'top', :'data-intro' => 'Buscar por nombre' }
          = f.text_field :search_query,
                         class: 'filterrific-periodically-observed form-control',
                         placeholder: 'Busqueda'
      .col-md-4
        .form-group.chardin_box{ :'data-position' => 'bottom', :'data-intro' => 'Restablecer los ajustes del filtro a los valores predeterminados.' }
          = link_to "Restablecer los filtros", reset_filterrific_url, :class => 'btn btn-default btn-sm'
          = link_to "Nueva Profesion", new_profesion_path, :class => "btn btn-primary"

#results
  = render partial: 'profesiones/list',
           locals: { :profesiones => @profesiones }

:javascript
  $('#overlayTrigger').click(function(event) {
    event.preventDefault();
    $('body').chardinJs('start');
  });

app/views/profesiones/index.js.erb
<% js = escape_javascript(
  render(
  	:partial => 'profesiones/list',
  	:locals => { :profesiones => @profesiones }
  )
) %>
$("#results").html("<%= js %>");

app/views/profesiones/new.html.haml
%h1 Nueva Profesion

= render 'form'

= link_to 'Atras', profesiones_path

app/views/profesiones/show.html.haml
%p#notice= notice

%p
  %b Codigo:
  = @profesion.codigo
%p
  %b Nombre:
  = @profesion.nombre

= link_to 'Editar', edit_profesion_path(@profesion)
\|
= link_to 'Atras', profesiones_path