config/routes.rb
Rails.application.routes.draw do
  resources :personas
  resources :profesiones
  devise_for :users

  resources :barrios
  resources :ciudades do
    get 'search'
  end
  get 'principal/index'
 
  root :to => 'principal#index'

end

app/models/persona.rb
class Persona < ActiveRecord::Base
  belongs_to :ciudad
  belongs_to :barrio
  belongs_to :profesion

	validates :nroiden, :presence => {:message => "Usted debe ingresar Doc. Identidad"}, length: {minimum: 5, maximum: 15, :message => "El Doc. Identidad debe tener entre 5 y 15 caracteres"}
	validates :pri_ape, :presence => {:message => "Usted debe ingresar Primer Apellido"}, length: {minimum: 5, maximum: 20, :message => "El 1er.Apellido debe tener entre 5 y 20 caracteres"}
	validates :pri_nom, :presence => {:message => "Usted debe ingresar Primer Nombre"}, length: {minimum: 5, maximum: 20, :message => "El 1er.Nombre debe tener entre 5 y 20 caracteres"}

  filterrific :default_filter_params => { :sorted_by => 'apellidos_asc' },
              :available_filters => %w[
                sorted_by
                search_query
              ]
  #             with_estado_id

  # default for will_paginate
  self.per_page = 10

  scope :search_query, lambda { |query|
    return nil  if query.blank?
    # condición de consulta, analizar en cada palabra clave
    terms = ('%' + query.downcase).split(/\s+/)
    # reemplazar "*" con "%" para las búsquedas de comodín,
    # añadir '%', eliminar duplicados '%'s
    terms = terms.map { |e|
      (e.gsub('*', '%') + '%').gsub(/%+/, '%')
    }
    # configurar varias condiciones o para la prestación
    # de los argumentos de interpolación. Ajuste esto si
    # cambiar el número de condiciones o.
    num_or_conditions = 4
    where(
      terms.map {
        or_clauses = [
          "LOWER(personas.pri_ape) LIKE ?",
          "LOWER(personas.seg_ape) LIKE ?",
          "LOWER(personas.pri_nom) LIKE ?",
          "LOWER(personas.seg_nom) LIKE ?"
        ].join(' OR ')
        "(#{ or_clauses })"
      }.join(' AND '),
      *terms.map { |e| [e] * num_or_conditions }.flatten
    )
  }
  
  scope :sorted_by, lambda { |sort_option|
    # extraer la dirección de ordenación del valor param.
    direction = (sort_option =~ /desc$/) ? 'desc' : 'asc'
    case sort_option.to_s
    when /^apellidos_/
      order("LOWER(personas.pri_ape) #{ direction }, LOWER(personas.seg_ape) #{ direction }")
    when /^nombres_/
      order("LOWER(personas.pri_nom) #{ direction }, LOWER(personas.seg_nom) #{ direction }")
    when /^documento_/
      order("personas.nroiden #{ direction }")
    else
      raise(ArgumentError, "Invalid sort option: #{ sort_option.inspect }")
    end
  }

  def self.options_for_sorted_by
    [
      ['Apellidos (a-z)', 'apellidos_asc'],
      ['Apellidos (z-a)', 'apellidos_desc'],
      ['Nombres (a-z)', 'nombres_asc'],
      ['Nombres (z-a)', 'nombres_desc'],
      ['Doc.Identidad', 'documento_asc']
    ]
  end

  def apellidos
    [pri_ape, seg_ape].compact.join(', ')
  end
  def nombres
    [pri_nom, seg_nom].compact.join(', ')
  end

end

app/controllers/personas_controller.rb
class PersonasController < ApplicationController
  before_action :set_persona, only: [:show, :edit, :update, :destroy]

  def index
    @fpersona = initialize_filterrific(
      Persona,
      params[:filterrific],
      :select_options => {
        sorted_by: Persona.options_for_sorted_by
      }
    ) or return
    @personas = @fpersona.find.page(params[:page])
    # @personas = Persona.all
    #    with_estado_id: Departamento.options_for_select

    # Respond to html for initial page load and to js for AJAX filter updates.
    respond_to do |format|
      format.html
      format.js
    end
  end

  def show
  end

  def new
    @persona = Persona.new
  end

  def edit
  end

  def create
    @persona = Persona.new(persona_params)

    respond_to do |format|
      if @persona.save
        format.html { redirect_to @persona, notice: 'Persona fue creada con éxito.' }
        format.json { render :show, status: :created, location: @persona }
      else
        format.html { render :new }
        format.json { render json: @persona.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @persona.update(persona_params)
        format.html { redirect_to @persona, notice: 'Persona fue actualizada correctamente.' }
        format.json { render :show, status: :ok, location: @persona }
      else
        format.html { render :edit }
        format.json { render json: @persona.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @persona.destroy
    respond_to do |format|
      format.html { redirect_to personas_url, notice: 'Persona fue borrada con éxito.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_persona
      @persona = Persona.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def persona_params
      params.require(:persona).permit(:tipoiden, :nroiden, :pri_ape, :seg_ape, :pri_nom, :seg_nom, :sexo, :fechanac, :uniedad, :edad, :zonaresi, :direccion, :email, :tipousua, :tipoafili, :est_civil, :estado, :ciudad_id, :barrio_id, :profesion_id)
    end
end

app/helpers/personas_helper.rb
module PersonasHelper
end

app/views/personas/_form.html.haml
= form_for @persona do |f|
  #error_explanation.bg-danger.text-danger
  .row
    .col-sm-offset-2
      .form-group
        = f.label 'Tipo Doc.'
        = f.select :tipoiden, options_for_select([["Cedula","CC"],["Ced.Extranjeria","CE"],["Pasaporte","PA"],["R.Civil","RC"],["Tarj.Identidad","TI"],["Adulto sin ID","AS"],["Menor sin ID","MS"],["Nro.Unico ID","NU"]])
        = f.label 'Doc.Identidad', :class => "control-label"
        = f.text_field :nroiden, :class => "form-control first_input", size: 15
      .form-group
        = f.label 'Primer Apellido'
        = f.text_field :pri_ape, :class => "form-control", :tabindex => -1
      .form-group
        = f.label 'Segundo Apellido'
        = f.text_field :seg_ape
      .form-group
        = f.label 'Primer Nombre'
        = f.text_field :pri_nom
      .form-group
        = f.label 'Segundo Nombre'
        = f.text_field :seg_nom
      .form-group
        = f.label :sexo
        = f.select :sexo, options_for_select([["Masculino","M"],["Femenino","F"]])
      .form-group
        = f.label 'Und.Medida Edad'
        = f.select :uniedad, options_for_select([["Años","1"],["Meses","2"],["Dias","3"]])
      .form-group
        = f.label :edad
        = f.number_field :edad
      .form-group
        = f.label 'Zona Residencia'
        = f.select :zonaresi, options_for_select([["Urbano","U"],["Rural","R"]])
      .form-group
        = f.label :direccion
        = f.text_field :direccion
      .form-group
        = f.label :email
        = f.email_field :email
      .form-group
        = f.label 'Tipo usuario'
        = f.select :tipousua, options_for_select([["Contributivo","1"],["Subsidiado","2"],["Vinculado","3"],["Particular","4"],["Otro","5"]])
      .form-group
        = f.label 'Tipo Afiliado'
        = f.select :tipoafili, options_for_select([["Cotizante","C"],["Beneficiario","B"],["Adicional","A"]])
      .form-group
        = f.label 'Estado civil'
        = f.select :est_civil, options_for_select([["Soltero","S"],["Casado","C"],["Viudo","V"],["Divorsiado","D"],["Otros","O"]])
      .form-group
        = f.label :estado
        = f.select :estado, options_for_select([["Activo",1],["Inactivo",2]])
      .form-group
        = f.label :ciudad
        = f.hidden_field :ciudad
      .form-group
        = f.label :barrio
        = f.hidden_field :barrio
      .form-group
        = f.label :profesion
        = f.hidden_field :profesion
      .form-group
        = f.submit @persona.new_record? ? "Crear persona." : "Actualizar persona.", :class => "btn btn-primary"

app/views/personas/_list.html.haml
.well.well-small
  .pull-left{ :'data-position' => 'bottom', :'data-intro' => 'Restablecer los ajustes del filtro a los valores predeterminados.' }
    = link_to "Restablecer los filtros", reset_filterrific_url, :class => 'btn btn-default btn-sm'

  .chardin_box{ :'data-position' => 'bottom', :'data-intro' => "Creacion de las Personas." }
    = link_to "Nueva Persona", new_persona_path, :class => "btn btn-primary"

%table.table.table-bordered.table-striped
  %tr
    %th Doc.Identidad
    %th Apellidos
    %th Nombres
    %th
  - personas.each do |persona|
    %tr
      %td= persona.nroiden
      %td= persona.apellidos
      %td= persona.nombres
      %td= link_to "Editar", edit_persona_path(persona), :class => "btn btn-primary"

.chardin_box{ :'data-position' => 'top', :'data-intro' => "Paginador de will_paginate funciona como se esperaba." }
  = will_paginate personas, renderer: BootstrapPagination::Rails

app/views/personas/edit.html.haml
%h1 Modificar Persona

= render 'form'

= link_to 'Mostrar', @persona
\|
= link_to 'Atras', personas_path

app/views/personas/index.html.haml
.page-header{ :style => 'margin-bottom: 0px;' }
  .pull-right
    = link_to 'Atras', root_path, :style => 'display: inline-block; margin-top: 25px;'
  %h1 Personas

.well
  = form_for_filterrific @fpersona do |f|
    .row
      .col-md-3
        .form-group.chardin_box{ :'data-position' => 'top', :'data-intro' => 'Buscar por Apellidos, Nombres' }
          %label Busqueda
          = f.text_field :search_query,
                         class: 'filterrific-periodically-observed form-control',
                         placeholder: 'Busqueda'
      .col-md-4
        .form-group.chardin_box{ :'data-position' => 'top', :'data-intro' => 'Cambie el orden.' }
          %label Ordenado por
          = f.select :sorted_by,
                     @fpersona.select_options[:sorted_by],
                     {},
                     { :class => 'form-control' }

#results
  = render :partial => 'personas/list',
           :locals => { :personas => @personas }

:javascript
  $('#overlayTrigger').click(function(event) {
    event.preventDefault();
    $('body').chardinJs('start');
  });

app/views/personas/index.js.erb
<% js = escape_javascript(
  render(
  	:partial => 'personas/list',
  	:locals => { :personas => @personas }
  )
) %>
$("#results").html("<%= js %>");

app/views/personas/new.html.haml
%h1 Nueva Persona

= render 'form'

= link_to 'Atras', personas_path

app/views/personas/show.html.haml
%p#notice= notice

%p
  %b Tipoiden:
  = @persona.tipoiden
%p
  %b Nroiden:
  = @persona.nroiden
%p
  %b Pri ape:
  = @persona.pri_ape
%p
  %b Seg ape:
  = @persona.seg_ape
%p
  %b Pri nom:
  = @persona.pri_nom
%p
  %b Seg nom:
  = @persona.seg_nom
%p
  %b Sexo:
  = @persona.sexo
%p
  %b Fechanac:
  = @persona.fechanac
%p
  %b Uniedad:
  = @persona.uniedad
%p
  %b Edad:
  = @persona.edad
%p
  %b Zonaresi:
  = @persona.zonaresi
%p
  %b Direccion:
  = @persona.direccion
%p
  %b Email:
  = @persona.email
%p
  %b Tipousua:
  = @persona.tipousua
%p
  %b Tipoafili:
  = @persona.tipoafili
%p
  %b Est civil:
  = @persona.est_civil
%p
  %b Estado:
  = @persona.estado
%p
  %b Ciudad:
  = @persona.ciudad
%p
  %b Barrio:
  = @persona.barrio
%p
  %b Profesion:
  = @persona.profesion

= link_to 'Edit', edit_persona_path(@persona)
\|
= link_to 'Back', personas_path