config/routes.rb
Rails.application.routes.draw do
  resources :personas
  resources :profesiones
  devise_for :users

  resources :barrios
  resources :ciudades do
    get 'search'
  end
  get 'principal/index'
 
  root :to => 'principal#index'

end

app/controllers/ciudades_controller.rb
class CiudadesController < ApplicationController
  before_action :set_ciudad, only: [:show, :edit, :update, :destroy]

  # GET /ciudades
  # GET /ciudades.json
  def index
    @fciudad = initialize_filterrific(
      Ciudad,
      params[:filterrific],
      :select_options => {
        sorted_by: Ciudad.options_for_sorted_by,
        with_departamento_id: Departamento.options_for_select
      }
    ) or return
    @ciudades = @fciudad.find.page(params[:page])
    # @ciudades = Ciudad.all

    # Respond to html for initial page load and to js for AJAX filter updates.
    respond_to do |format|
      format.html
      format.js
    end
  end

  # GET /ciudades/1
  # GET /ciudades/1.json
  def show
  end

  # GET /ciudades/new
  def new
    @ciudad = Ciudad.new
    @deptos = Departamento.select("id, nombre").order("nombre")
    #@tareas = Tarea.select("titulo, descripcion").where(:activo => true).order("titulo").limit(3);
  end

  # GET /ciudades/1/edit
  def edit
  end

  # POST /ciudades
  # POST /ciudades.json
  def create
    @ciudad = Ciudad.new(ciudad_params)

    respond_to do |format|
      if @ciudad.save
        format.html { redirect_to @ciudad, notice: 'Ciudad fue creada con éxito.' }
        format.json { render :show, status: :created, location: @ciudad }
      else
        format.html { render :new }
        format.json { render json: @ciudad.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ciudades/1
  # PATCH/PUT /ciudades/1.json
  def update
    respond_to do |format|
      if @ciudad.update(ciudad_params)
        format.html { redirect_to @ciudad, notice: 'Ciudad fue actualizada correctamente.' }
        format.json { render :show, status: :ok, location: @ciudad }
      else
        format.html { render :edit }
        format.json { render json: @ciudad.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ciudades/1
  # DELETE /ciudades/1.json
  def destroy
    @ciudad.destroy
    respond_to do |format|
      format.html { redirect_to ciudades_url, notice: 'Ciudad fue borrada con éxito.' }
      format.json { head :no_content }
    end
  end

  def search
    @ciudad = Ciudad.find_by!(codigo: params[:ciudad_id])
    respond_to do |format|
      format.json { render :json => @ciudad }
    end 
  end 

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ciudad
      @ciudad = Ciudad.find(params[:id])
    end
  
    # Never trust parameters from the scary internet, only allow the white list through.
    def ciudad_params
      params.require(:ciudad).permit(:codigo, :nombre, :departamento_id)
    end
end

app/helpers/ciudades_helper.rb
module CiudadesHelper
end

app/views/ciudades/_dialog.html.erb
<div class="modal fade"
           id="dialog" tabindex="-1" role="dialog" 
           aria-labelledby="myModalLabel"
           aria-hidden="true" 
           data-backdrop="static" 
           data-keyboard="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" 
                data-dismiss="modal" 
                aria-label="Close">
                <span aria-hidden="true">&times;</span></button>
        <h3 class="modal-title"></h3>
      </div>
      <div class="modal-body">
      </div>
     
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/ciudades/_form.html.haml
= form_for @ciudad do |f|
  #error_explanation.bg-danger.text-danger
  .row
    .col-sm-6
      .form-group
        = f.label :departamento, :class => "control-label"
        = collection_select(:ciudad, :departamento_id, @deptos, :id, :nombre, {prompt: 'Selecione departamento'})
      .form-group
        = f.label :codigo, :class => "control-label"
        = f.text_field :codigo, :class => "form-control first_input"
      .form-group
        = f.label :nombre, :class => "control-label"
        = f.text_field :nombre, :class => "form-control"
      .form-group
        = f.submit  @ciudad.new_record? ? "Crear ciudad" : "Actualizar ciudad", :class => "btn btn-primary"

app/views/ciudades/_list.html.haml
.well.well-small
  .pull-left{ :'data-position' => 'bottom', :'data-intro' => 'Restablecer los ajustes del filtro a los valores predeterminados.' }
    = link_to "Restablecer los filtros", reset_filterrific_url, :class => 'btn btn-default btn-sm'

  .chardin_box{ :'data-position' => 'bottom', :'data-intro' => "Creacion de las Ciudades." }
    = link_to "Nueva Ciudad", new_ciudad_path, :class => "btn btn-primary"

%table.table.table-bordered.table-striped
  %tr
    %th Nombre
    %th Codigo
    %th Departamento
    %th
  - ciudades.each do |ciudad|
    %tr
      %td= ciudad.nombre
      %td= ciudad.codigo
      %td= ciudad.departamento_nombre.capitalize
      %td= link_to "Editar", edit_ciudad_path(ciudad), :class => "btn btn-primary"

.chardin_box{ :'data-position' => 'top', :'data-intro' => "Paginador de will_paginate funciona como se esperaba." }
  = will_paginate ciudades, renderer: BootstrapPagination::Rails

app/views/ciudades/edit.html.haml
%h1 Modificar Ciudad

= render 'form'

= link_to 'Mostrar', @ciudad
\|
= link_to 'Atras', ciudades_path

app/views/ciudades/index.html.haml
.page-header{ :style => 'margin-bottom: 0px;' }
  .pull-right
    = link_to 'Atras', root_path, :style => 'display: inline-block; margin-top: 25px;'
  %h1 Ciudades

.well
  = form_for_filterrific @fciudad do |f|
    .row
      .col-md-3
        .form-group.chardin_box{ :'data-position' => 'top', :'data-intro' => 'Buscar por nombre, codigo.' }
          %label Busqueda
          = f.text_field :search_query,
                         class: 'filterrific-periodically-observed form-control',
                         placeholder: 'Busqueda'
      .col-md-3
        .form-group.chardin_box{ :'data-position' => 'top', :'data-intro' => 'Filtrar por Departamento.' }
          %label Departamento
          = f.select :with_departamento_id,
                     @fciudad.select_options[:with_departamento_id],
                     { :include_blank => '- Cualquier -' },
                     { :class => 'form-control' }
      .col-md-4
        .form-group.chardin_box{ :'data-position' => 'top', :'data-intro' => 'Cambie el orden.' }
          %label Ordenado por
          = f.select :sorted_by,
                     @fciudad.select_options[:sorted_by],
                     {},
                     { :class => 'form-control' }

#results
  = render :partial => 'ciudades/list',
           :locals => { :ciudades => @ciudades }

:javascript
  $('.js-datepicker').datepicker();
  $('#overlayTrigger').click(function(event) {
    event.preventDefault();
    $('body').chardinJs('start');
  });

app/views/ciudades/index.js.erb
<% js = escape_javascript(
  render(
  	:partial => 'ciudades/list',
  	:locals => { :ciudades => @ciudades }
  )
) %>
$("#results").html("<%= js %>");

app/views/ciudades/new.html.haml
%h1 Nueva Ciudad

= render 'form'

= link_to 'Atras', ciudades_path

app/views/ciudades/show.html.haml
%p#notice= notice

%p
  %b Codigo:
  = @ciudad.codigo
%p
  %b Nombre:
  = @ciudad.nombre
%p
  %b Departamento:
  = @ciudad.departamento_nombre.capitalize

= link_to 'Editar', edit_ciudad_path(@ciudad)
\|
= link_to 'Atras', ciudades_path