config/routes.rb
Rails.application.routes.draw do
  resources :personas
  resources :profesiones
  devise_for :users

  resources :barrios
  resources :ciudades do
    get 'search'
  end
  get 'principal/index'
 
  root :to => 'principal#index'

end

app/models/barrio.rb
class Barrio < ActiveRecord::Base
  belongs_to :ciudad
  has_many :personas
	validates :nombre, :presence => {:message => "Usted debe ingresar un nombre"}, length: {minimum: 5, maximum: 100, :message => "El nombre debe tener entre 2 y 60 caracteres"}

  filterrific :default_filter_params => { :sorted_by => 'nombre_asc' },
              :available_filters => %w[
                sorted_by
                search_query
                with_ciudad_id
              ]

  # default for will_paginate
  self.per_page = 10

  scope :search_query, lambda { |query|
    return nil  if query.blank?
    # condición de consulta, analizar en cada palabra clave
    terms = ('%' + query.downcase).split(/\s+/)
    # reemplazar "*" con "%" para las búsquedas de comodín,
    # añadir '%', eliminar duplicados '%'s
    terms = terms.map { |e|
      (e.gsub('*', '%') + '%').gsub(/%+/, '%')
    }
    # configurar varias condiciones o para la prestación
    # de los argumentos de interpolación. Ajuste esto si
    # cambiar el número de condiciones o.
    num_or_conditions = 1
    where(
      terms.map {
        or_clauses = [
          "LOWER(barrios.nombre) LIKE ?"
        ].join(' OR ')
        "(#{ or_clauses })"
      }.join(' AND '),
      *terms.map { |e| [e] * num_or_conditions }.flatten
    )
  }

	scope :sorted_by, lambda { |sort_option|
    # extraer la dirección de ordenación del valor param.
    direction = (sort_option =~ /desc$/) ? 'desc' : 'asc'
    case sort_option.to_s
   when /^nombre_/
      order("LOWER(barrios.nombre) #{ direction }")
   else
      raise(ArgumentError, "Opción de clasificación válido: #{ sort_option.inspect }")
    end
  }
  scope :with_ciudad_id, lambda { |ciudad_ids|
    where(:ciudad_id => [*ciudad_ids])
  }

end

app/controllers/barrios_controller.rb
class BarriosController < ApplicationController
  before_action :set_barrio, only: [:show, :edit, :update, :destroy]
  #before_filter :authenticate_user! except: [ :index, :show ]
 
  #def barriosof
  #  @ciudad_id = params[:ciudad_id]
  #  @ciudad = Ciudad.find(@ciudad_id)
  #  @barrios = @ciudad.id
  # (59) barriosof_path(@barrio.ciudad.id)
  #end

  def index
    @fbarrio = initialize_filterrific(
      Barrio,
      params[:filterrific]
    ) or return
    @barrios = @fbarrio.find.page(params[:page])
    # @barrios = Barrio.where(:ciudad_id => 126).order("nombre")

    # Respond to html for initial page load and to js for AJAX filter updates.
    respond_to do |format|
      format.html
      format.js
    end
  end

  def show
  end

  def new
    @barrio = Barrio.new
    #@ciudad = Ciudad.all
  end

  def edit
  end

  def create
    @barrio = Barrio.new(barrio_params)

    respond_to do |format|
      if @barrio.save
        format.html { redirect_to @barrio, notice: 'Barrio fue creado con éxito.' }
        format.json { render :show, status: :created, location: @barrio }
      else
        format.html { render :new }
        format.json { render json: @barrio.errors, status: :unprocessable_entity }
      end
    end

  end

  def update
    respond_to do |format|
      if @barrio.update(barrio_params)
        format.html { redirect_to @barrio, notice: 'Barrio fue actualizado correctamente.' }
        format.json { render :show, status: :ok, location: @barrio }
      else
        format.html { render :edit }
        format.json { render json: @barrio.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @barrio.destroy
    respond_to do |format|
      format.html { redirect_to ciudades_url, notice: 'Barrio fue borrado con éxito.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_barrio
      @barrio = Barrio.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def barrio_params
      params.require(:barrio).permit(:nombre, :ciudad_id, :created_at, :updated_at)
    end
end

app/helpers/barrios_helper.rb
module BarriosHelper
end

app/views/barrios/_form.html.haml
= form_for @barrio do |f|
  #error_explanation.bg-danger.text-danger
  .row
    .col-sm-6
      .form-group
        = f.label :nombre, :class => "control-label"
        = f.text_field :nombre, :class => "form-control first_input"
      .form-group
        = f.submit  @barrio.new_record? ? "Crear barrio" : "Actualizar barrio", :class => "btn btn-primary"

app/views/barrios/_list.html.haml
%table.table.table-bordered.table-striped
  %tr
    %th Nombre
    %th
  - barrios.each do |barrio|
    %tr
      %td= barrio.nombre
      %td= link_to "Editar", edit_barrio_path(barrio), :class => "btn btn-primary"

.chardin_box{ :'data-position' => 'top', :'data-intro' => "Paginador de will_paginate funciona como se esperaba." }
  = will_paginate barrios, renderer: BootstrapPagination::Rails

app/views/barrios/edit.html.haml
%h1 Modificar barrio

= render 'form'

= link_to 'Mostrar', @barrio
\|
= link_to 'Atras', barrios_path

app/views/barrios/index.html.haml
.page-header{ :style => 'margin-bottom: 0px;' }
  .pull-right
    = link_to 'Home', root_path, :style => 'display: inline-block; margin-top: 25px;'
  %h1 Barrios

.well
  = form_for_filterrific @fbarrio do |f|
    .row
      .col-md-3
        .form-group.chardin_box{ :'data-position' => 'top', :'data-intro' => 'Buscar por nombre' }
          = f.text_field :search_query,
                         class: 'filterrific-periodically-observed form-control',
                         placeholder: 'Busqueda'
      .col-md-4
        .form-group.chardin_box{ :'data-position' => 'bottom', :'data-intro' => 'Restablecer los ajustes del filtro a los valores predeterminados.' }
          = link_to "Restablecer los filtros", reset_filterrific_url, :class => 'btn btn-default btn-sm'
          = link_to "Nuevo barrio", new_barrio_path, :class => "btn btn-primary"

#results
  = render partial: 'barrios/list',
           locals: { :barrios => @barrios }

:javascript
  $('#overlayTrigger').click(function(event) {
    event.preventDefault();
    $('body').chardinJs('start');
  });

app/views/barrios/index.js.erb
<% js = escape_javascript(
  render(
  	:partial => 'barrios/list',
  	:locals => { :barrios => @barrios }
  )
) %>
$("#results").html("<%= js %>");

app/views/barrios/new.html.haml
%h1 Nuevo Barrio

= render 'form'

= link_to 'Atras', barrios_path

app/views/barrios/show.html.haml
%p#notice= notice

%p
  %b Nombre:
  = @barrio.nombre
%p
  %b Ciudad:
  = @barrio.ciudad.nombre

= link_to 'Editar', edit_barrio_path(@barrio)
\|
= link_to 'Atras', barrios_path

app/views/barrios/zcreate.js.erb
$('#dialog').modal('toggle');
$('#barrios').append('<%= j render (@barrio) %>')

app/views/barrios/zedit.js.erb
// Add the dialog title
$('#dialog h3').html("<i class=' glyphicon glyphicon-pencil'></i> Modificar Barrio");
 
// Render the edit form
$('.modal-body').html('<%= j render("form") %>');
 
// Show the dynamic dialog
$('#dialog').modal("show");
 
// Set focus to the first element
$('#dialog').on('shown.bs.modal', function () {
	  $('.first_input').focus()
  })

app/views/barrios/znew.js.erb
// Add the dialog title
$('#dialog h3').html("<i class='glyphicon glyphicon-plus'></i> Adiciona Nuevo Barrio");
 
// Render the new form
$('.modal-body').html('<%= j render("form") %>');
 
// Show the dynamic dialog
$('#dialog').modal("show");
 
// Set focus to the first element
$('#dialog').on('shown.bs.modal', function () {
	  $('.first_input').focus()
  })